# Generated by Django 4.1.7 on 2023-03-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['uuid'], 'verbose_name': 'Comprador', 'verbose_name_plural': 'Compradores'},
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='cookie',
            new_name='uuid',
        ),
    ]
