# Generated by Django 4.1.7 on 2023-03-04 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_buyer_options_rename_cookie_buyer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
