# Generated by Django 4.1.7 on 2023-03-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_alter_buyer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name='UUID'),
        ),
    ]
