# Generated by Django 4.1.7 on 2023-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased',
            field=models.BooleanField(default=False, verbose_name='Comprado'),
        ),
    ]
